# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit RepLing.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE)


## ----loading data, echo=TRUE--------------------------------------------------
# loading the data and having a glimpse
coded_articles = read.csv("../data/Coding_Articles.csv", sep="|")

head(coded_articles)

