---
title: Replication studies in experimental linguistic journals
shorttitle: ReplicationLing
shortauthors: Kobrock & Roettger
author:
- name: Kristina Kobrock
  affiliation: University of Osnabrück
  address: kkobrock@uni-osnabrueck.de
- name: Timo B. Roettger
  affiliation: University of Oslo
classoption: [cm]
bibliography: references.bib
#abstract: |
  #to be written (100-300 words/ no more than 250 words)
keywords: replication, experimental linguistics, ... # about 5 keywords/ up to 6
# wordcount: 1000 (no more than 13.000)
output: 
  rticles::glossa_article:
    citation_package: natbib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction

# Overview analysis: Rate of replication mention
## Research questions
## Sample
## Procedure
## Data Analysis
## Results

# Detailed analysis: Types and contributing factors
## Research questions
## Sample
## Procedure
## Data Analysis
```{r loading data, echo=TRUE}
# loading the data and having a glimpse
coded_articles = read.csv("../data/Coding_Articles.csv", sep="|")

head(coded_articles)
```
## Results

# Discussion

# Conclusion

<!--
# Abbreviations (mandatory if applicable) {#abbrev .unnumbered}

# Data availability/Supplementary files (optional) {#data-availabilitysupplementary-files-optional .unnumbered}

# Ethics and consent (optional) {#ethics-and-consent-optional .unnumbered}

# Funding information (optional) {#funding-information-optional .unnumbered}

# Acknowledgements (optional) {#acknowledgements-optional .unnumbered}

# Competing interests (mandatory) {#competing-interests-mandatory .unnumbered}

# Authors' contributions (optional) {#contrib .unnumbered}
-->

# References {#sec:refs .unnumbered}

<!--Glossa style in Citation Style Language (CSL) is available
[here](https://www.zotero.org/styles?q=Glossa). Many thanks to Mark
Dingemanse for creating this style.-->